#include "MoonApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<MoonApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

MoonApp::MoonApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  MoonApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  MoonApp::associateSyntax(_syntax, _action_factory);
}

MoonApp::~MoonApp()
{
}

// External entry point for dynamic application loading
extern "C" void MoonApp__registerApps() { MoonApp::registerApps(); }
void
MoonApp::registerApps()
{
  registerApp(MoonApp);
}

// External entry point for dynamic object registration
extern "C" void MoonApp__registerObjects(Factory & factory) { MoonApp::registerObjects(factory); }
void
MoonApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void MoonApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { MoonApp::associateSyntax(syntax, action_factory); }
void
MoonApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
